--
-- Dumping data for table html_portlet
--

INSERT INTO `html_portlet` VALUES (1, '');
INSERT INTO `html_portlet` VALUES (2, '<ul class="features"> \n <li>Lutece is FreeSoftware. Full OpenSource licensed under BSD.</li> \n <li>Full responsive design Back and Front</li> \n <li>Compliant with Bootstrap 3.x themes</li> \n <li>Very modular and flexible architecture based on plugins, APIs, IoC</li> \n <li>Over 300 plugins available for many needs : Content Management, Collaborative, Workflows, ...</li> \n <li>Runs on Java Platform and rely on powerful build tools such as Apache Maven</li> \n <li>Uses best of breed Java Open Source stacks : Lucene, Spring, Ehcache, Freemarker, ...</li> \n</ul> \n<p class="logo"><img class="img-responsive logo" title="Lutece" src="images/lutece_banner.png" alt=""></p>');
INSERT INTO `html_portlet` VALUES (4, '<h2>Go and log in as "admin" or "webmaster".</h2> \n<p class="mb20">The password is "adminadmin".<br> The "admin" user has all rights and features, whereas the "webmaster" user can only work on the editorial content of the site.</p> \n<p><a class="btn btn-outline-primary" title="Access to admin " href="jsp/admin/AdminLogin.jsp"><span class="fa fa-plug">&nbsp;</span> Display Admin Login Form</a></p> \n<h2>Documentation</h2> \n<p>Find useful resources on the wiki <a href="http://wiki.lutece.paris.fr/" target="_blank">Documentation</a></p> \n<h2>Get you own copy</h2> \n<p><img src="images/local/skin/docker-lutece.png" alt="" height="24px"> A docker package is available on the <a title="Docker repository" href="https://registry.hub.docker.com/u/lutece/lutece-demo/" target="_blank">Docker repository</a>. Deploy a packaged site on your own application server like Apache Tomcat <img src="images/tomcat.png" alt="" height="24px">. Get a war from the<a title=" Lutece Appstore" href="jsp/site/Portal.jsp?page=appstore" target="_blank"> Lutece Appstore</a>.</p>');
INSERT INTO `html_portlet` VALUES (5, '<h3>Examples from several plugins</h3> \n<hr> \n<div class="row"> \n <div class="col-xs-12 col-sm-6"> \n  <div class="media"> \n   <div class="media-left">\n    <a href="#"> <img class="media-object" src="images/lutece_icon_square.png" alt="Form" height="64px"> </a>\n   </div> \n   <div class="media-body"> \n    <h4 class="media-heading">View a form built with the Form plugin.</h4> \n    <p>An example of a simple form. <a title="Follow the guide" href="jsp/site/Portal.jsp?page=form&amp;&amp;id_form=1" target="_blank">Follow the guide</a></p> \n   </div> \n  </div> \n  <div class="media"> \n   <div class="media-left">\n    <a href="#"> <img class="media-object" src="images/lutece_icon_square.png" alt="Suggests" height="64px"> </a>\n   </div> \n   <div class="media-body"> \n    <h4 class="media-heading">Participate, vote by responding to the consultation created by the Suggests plugin.</h4> \n    <p>Give your opinion on any subject <a title="Follow the guide" href="jsp/site/Portal.jsp?page=suggest&amp;id_suggest=1" target="_blank">Follow the guide</a></p> \n   </div> \n  </div> \n </div> \n <div class="col-xs-12 col-sm-6"> \n  <div class="media"> \n   <div class="media-left">\n    <a href="#"> <img class="media-object" src="images/lutece_icon_square.png" alt="WIKI" height="64px"> </a>\n   </div> \n   <div class="media-body"> \n    <h4 class="media-heading">Enrich your content in a participatory way with the WIKI plugin.</h4> \n    <p>Read notices, write and update content. <a title="Follow the guide" href="jsp/site/Portal.jsp?page=wiki" target="_blank">Follow the guide</a></p> \n   </div> \n  </div> \n  <div class="media"> \n   <div class="media-left">\n    <a href="#"> <img class="media-object" src="images/lutece_icon_square.png" alt="PluginWizard" height="64px"> </a>\n   </div> \n   <div class="media-body"> \n    <h4 class="media-heading">Create my first plugin !</h4> \n    <p>You can easily create your first plugin, feature, in a few clicks. <a title="Follow the guide" href="jsp/site/Portal.jsp?page=pluginwizard" target="_blank">Follow the guide</a></p> \n   </div> \n  </div> \n </div> \n</div>');

